Added json format option

diff --git a/src/in b/src/in
--- a/src/in
+++ b/src/in
@@ -10,9 +10,15 @@ input_json="$(cat)"
 response=
 repository_total_count=
 
-org=$(              echo "${input_json}" | jq '.source.org'             -r)
-team=$(             echo "${input_json}" | jq '.source.team? // empty'  -r)
-requested_hash=$(   echo "${input_json}" | jq '.version.hash'           -r)
+org=$(              echo "${input_json}" | jq '.source.org'                     -r)
+team=$(             echo "${input_json}" | jq '.source.team? // empty'          -r)
+requested_hash=$(   echo "${input_json}" | jq '.version.hash'                   -r)
+output_format=$(    echo "${input_json}" | jq '.params.output_format? // "txt"' -r)
+
+if [[ "${output_format}" != "txt" ]] && [[ "${output_format}" != "json" ]]; then
+    echo "[ERROR] An illegal format [${output_format}] was specified. Only json and txt are supported!" 1>&2
+    exit 1
+fi
 
 github_api_response=$(query_github_list_repos "${input_json}")
 current_version_hash=$(echo ${github_api_response} | version_hash)
@@ -31,7 +37,15 @@ fi
 repository_total_count=$(cat /tmp/repositoryTotalCount.txt)
 rm -f /tmp/repositoryTotalCount.txt
 
-echo ${github_api_response} | tr ' ' '\n' > ${destination_dir}/repository-list.txt
+if [[ ${output_format} == "txt" ]]; then
+  echo ${github_api_response} | tr ' ' '\n' > ${destination_dir}/repository-list.txt
+elif [[ ${output_format} == "json" ]]; then
+  echo ${github_api_response} | jq -R -s 'split("\n")' > ${destination_dir}/repository-list.json
+else
+  echo "[ERROR] This should be impossible! output_format is set to an unsupported format [${output_format}] and was not caught during validation. Please report this to the developers!" 1>&2
+  rm -f /tmp/repositoryTotalCount.txt
+  exit 1
+fi
 
 # construct the final output
 output="{"
